apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-df
spec:
  runLatest:
    configuration:
      build:
        source:
          git:
            url: https://github.com/mchmarny/frnksgr/helloworld.git
            revision: master
        template:
          name: kaniko
          arguments:
          - name: IMAGE
            value: &image gcr.io/sap-cp-gke/helloworld-df:latest
      revisionTemplate:
        spec:
          container:
            image: *image
            imagePullPolicy: Always
