apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-kn-df
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        source:
          git:
            url: https://github.com/frnksgr/helloworld.git
            revision: master
        template:
          name: kaniko
          arguments:
          - name: IMAGE
            value: &image gcr.io/sap-cp-gke/helloworld-kn-df:latest
      revisionTemplate:
        #metadata:
        #  labels:
        #    knative.dev/type: app
        spec:
          container:
            image: *image
            imagePullPolicy: Always
            env:
            - name: FROM
              value: knative-dockerfile
