---
applications:
- name: helloworld-bp
  buildpacks: 
  - go_buildpack
  path: ../..
  memory: 32M
  disk_quota: 100M
  instances: 2
  env:
    GOPACKAGENAME: helloworld
    FROM: cloudfoundry-buildpack
    GOVERSION: go1.12
