---
applications:
- name: hellworld-ci
  memory: 32M
  disk_quota: 100M
  instances: 2
  docker:
    image: docker.io/frnksgr/helloworld-cf
  env:
    FROM: cloudfoundry-containerimage
    GOVERSION: go1.11
