---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: frnksgr/helloworld
        ports:
        - containerPort: 8080
        env:
        - name: FROM
          value: kubernetes-native

---
kind: Service
apiVersion: v1
metadata:
  name:  helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  selector:
    app:  helloworld
  #type:  ClusterIP
  #Error during sync: error while evaluating the ingress spec: service "default/helloworld" is type "ClusterIP", expected "NodePort" or "LoadBalancer"
  type: NodePort
  sessionAffinity: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  namespace: default
#  annotations:
     # selecting a specific ingress controller
#    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "helloworld.default.example.com"
    http:
      paths: 
      - path: /
        backend:
          serviceName: helloworld
          servicePort: 80
